#ifndef VERSUS_CONFIG_H
#define VERSUS_CONFIG_H

#include "game/config.h"

/*
 * Tunable values for the whole example live here so beginners can change the
 * demo without searching through gameplay, rendering and platform code.
 */
enum {
    VERSUS_PLAYER_COUNT = 2,
    VERSUS_NPC_CAPACITY = 0,
    VERSUS_OBJECT_CAPACITY = 0,
    VERSUS_PROJECTILE_CAPACITY = 0,

    VERSUS_ACTOR_CAPACITY = U_GAME_ACTOR_CAPACITY(VERSUS_PLAYER_COUNT, VERSUS_NPC_CAPACITY, VERSUS_OBJECT_CAPACITY, VERSUS_PROJECTILE_CAPACITY),
    VERSUS_COLLISION_LAYER_CAPACITY = U_GAME_COLLISION_LAYER_STORAGE_CAPACITY(VERSUS_PLAYER_COUNT, VERSUS_NPC_CAPACITY, VERSUS_OBJECT_CAPACITY, VERSUS_PROJECTILE_CAPACITY),
    VERSUS_COLLISION_QUERY_CAPACITY = U_GAME_COLLISION_QUERY_STORAGE_CAPACITY(VERSUS_PLAYER_COUNT, VERSUS_NPC_CAPACITY, VERSUS_OBJECT_CAPACITY, VERSUS_PROJECTILE_CAPACITY),

    VERSUS_MAX_HEALTH = 100,
    VERSUS_ROUNDS_TO_WIN = 2,
    VERSUS_ROUND_SECONDS = 60,
    VERSUS_INTRO_SECONDS = 2,
    VERSUS_OUTRO_SECONDS = 2,

    VERSUS_GROUND_Y = 184,
    VERSUS_STAGE_LEFT = 24,
    VERSUS_STAGE_RIGHT = 296,
    VERSUS_PLAYER_1_START_X = 92,
    VERSUS_PLAYER_2_START_X = 228,
    VERSUS_PUSHBOX_DISTANCE = 24,

    VERSUS_WALK_SPEED = 2,
    VERSUS_JUMP_SPEED = -7,
    VERSUS_JUMP_HORIZONTAL_SPEED = 2,
    VERSUS_GRAVITY = 1,

    VERSUS_SPRITE_ANCHOR_X = -32,
    VERSUS_SPRITE_ANCHOR_Y = -64,

    /* Power-of-two size keeps command-history wrapping to one cheap mask. */
    VERSUS_INPUT_BUFFER_CAPACITY = 16,
    VERSUS_INPUT_BUFFER_MASK = VERSUS_INPUT_BUFFER_CAPACITY - 1,
    VERSUS_QCF_WINDOW = 10,
};

#endif
